export default {
  "login": "MohammedDaFirst",
  "id": 88050045,
  "node_id": "MDQ6VXNlcjg4MDUwMDQ1",
  "avatar_url": "https://avatars.githubusercontent.com/u/88050045?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MohammedDaFirst",
  "html_url": "https://github.com/MohammedDaFirst",
  "followers_url": "https://api.github.com/users/MohammedDaFirst/followers",
  "following_url": "https://api.github.com/users/MohammedDaFirst/following{/other_user}",
  "gists_url": "https://api.github.com/users/MohammedDaFirst/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MohammedDaFirst/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MohammedDaFirst/subscriptions",
  "organizations_url": "https://api.github.com/users/MohammedDaFirst/orgs",
  "repos_url": "https://api.github.com/users/MohammedDaFirst/repos",
  "events_url": "https://api.github.com/users/MohammedDaFirst/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MohammedDaFirst/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Call me Lucien",
  "company": "Life",
  "blog": "",
  "location": "Here and there",
  "email": null,
  "hireable": null,
  "bio": "i do stuff.. good stuff",
  "twitter_username": "iiluciferq",
  "public_repos": 15,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-07-27T16:32:44Z",
  "updated_at": "2022-12-07T13:49:20Z"
}